### ISSUE TITLE
High score ties

### ISSUE THREAD

**Issue by Bboy111444** [thawkin3/crossyBlock#8]
@thawkin3 When a user scores the same as another high score on the leader board the user either replaces the score tied with or gets placed below that high score. There isn't a definitive way to track whether a score should be replaced above or below in a tie or whether names are placed alphabetically has any impact on above or below other scores. 

Failed Test Case: Score Board logs the top 10 scores (CB-13)

**Comment by thawkin3** [comment]
@Bboy111444 Thanks, that's a good point. Right now I'm just sorting it by the score but no other criteria. I'm going to have it sort by score and then by date recorded, with the newest scores first. That way players are incentivized to keep playing in order to keep their scores on the board.

**Comment by thawkin3** [comment]
@Bboy111444 This is fixed now. I tested locally and it's looking great. In order for you to re-test you'd need to get some high scores on the leaderboard and verify that they get sorted with the newest scores first, so if that's a bit difficult, I've added some screenshots as evidence that it's working:

![screen shot 2018-08-16 at 12 35 19 pm](https://user-images.githubusercontent.com/13806458/44227974-44977680-a151-11e8-8ee6-9ffc811227db.png)
![screen shot 2018-08-16 at 12 35 42 pm](https://user-images.githubusercontent.com/13806458/44227975-44977680-a151-11e8-80ee-2a5be5ac94b3.png)
